### ISSUE TITLE
Supprimer un plugin

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#115]
Magix CMS permet d'installer des plugins et il serait intéressant de pouvoir les désinstaller proprement.
La désinstallation lancerait la même procédure que l'installation mais avec un ficher sql désinstallation dans le cas ou des tables particulières serait présente mais également dans les tables core qui liste le plugin.

**Comment by Xarksass** [comment]
Le système à été mis en place, il reste à créer les fichier uninstall.sql pour les différent plugin.
Exemple sur mainsectors.
