### ISSUE TITLE
Réécriture SEO

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#116]
Dans l'admin, l'espace gestion SEO récupère :
1. ID 
2. Le module
3. Le niveau
4. Le type
5. Les actions

Il faudrait également remonter le contenu de la réécriture comme c'était le cas dans la V2 (voir capture).
![image](https://user-images.githubusercontent.com/30520312/56741661-962de180-6773-11e9-8ace-a4c363d4aa75.png)

**Comment by Xarksass** [comment]
L'affichage du contenu à été ajouté à la liste des élément remontés dans le listing.
