### ISSUE TITLE
Formulaire de contact par langue

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#118]
Lorsque l'on ajoute un destinataire de formulaire de contact, il est possible de l'assigner à une langue. Si la personne doit recevoir les formulaires en provenance de plusieurs langues il faut lui créer plusieurs insertions ?
Dans le tableau n'est pas remonté la langue assignée à l'adresse mail.
![image](https://user-images.githubusercontent.com/30520312/57026542-62066500-6c3a-11e9-8f83-d6f73d9e261d.png)

**Comment by Xarksass** [comment]
Normalement quand on ajoute un destinataire au formulaire de contact on ne lui assigne pas une langue, on active ou désactive le destinaire en fonction de la langue, ce qui permet effectivement que le destinataire reçoive tous les messages où seulement ceux dans une ou plusieurs langues spécifiquement.
