### ISSUE TITLE
Bug suppression multiple table-form

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#126]
Lorsque nous effectuons la sélection des lignes avec le "check-all" pour la suppression celui-ci est pris en compte dans la requête et elle n'aboutis pas.
Les logs affiche que "on" passe dans les identifiants numériques

**Comment by gtraxx** [comment]
Ce bug n'est toujours pas réglé

**Comment by Xarksass** [comment]
Visiblement on l'a réglé entre temps.

À noter, ceci est la structure à observer pour créer une section dans les variables de traductions

```
### Titre
ma_variable = Ma variable dans la section titre
```
