### ISSUE TITLE
Gestion du contenu de la page root du catalogue

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms-3#14]
Il faut penser à intégrer une gestion du contenu de la page root du catalogue, actuellement inexistant dans la v2.

**Comment by gtraxx** [comment]
Je vais me basé sur "About" la page root est stocker dans un table "data" avec des champs de configuration comme ce modèle.

![fireshot screen capture 102 - 10_0_0_58 _ localhost _ magixcms_3 _ mc_about_data i phpmyadmin 4_0_4 - 10_0_0_58_phpmyadmin_export_php pmaurl-1_tbl](https://user-images.githubusercontent.com/356674/28659086-680adc42-72ae-11e7-86f5-af11d4cac416.png)
