### ISSUE TITLE
Bug traduction statique avec commentaires

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#141]
Dans plugins et peut être dans le skin (a Vérifier)
si on a : 
```
ma_variable = truc machin
#### mon commentaire
mon_autre_variable = truc 
```
`#### mon commentaire` est converti en `mon commentaire =`  ce qui fait planter le système.

**Comment by Xarksass** [comment]
Visiblement on l'a réglé entre temps.

À noter, ceci est la structure à observer pour créer une section dans les variables de traductions

```
### Titre
ma_variable = Ma variable dans la section titre
```
