### ISSUE TITLE
Bug affichage megadropdown

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#143]
Dans le skin par défaut, le megadropdown ne s'affiche pas correctement si on le sélectionne, le menu doit apparaitre sur sa gauche ou sa droite mais il s'affiche en dessous du lien (un block sur un block).
<img width="327" alt="Capture d’écran 2021-01-14 à 22 37 48" src="https://user-images.githubusercontent.com/356674/104652274-2aaf4480-56b9-11eb-87ae-870b8e8664b3.png">

**Comment by Xarksass** [comment]
Petit correctif CSS mis en place.

À tester dans un cas pratique.

**Comment by gtraxx** [comment]
Allons nous le garder ou pas ? correctif non effectif mais utilité c'est Quid !!
