### ISSUE TITLE
json sendFeedback pas conforme

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#145]
Lorsque l'on utilise la **class progress** avec **sendFeedback** le système retourne un json, celui-ci n'étant pas conforme aux standard, il faudrait le rendre conforme, donc revoir la méthodologie d'affichage.
Celui-ci est actuellement utilisé pour le multi-upload des images mais aussi dans certains plugins.
### Exemple json non conforme : 
```json
{"message":"Contr\u00f4le des donn\u00e9es","progress":10}{"message":"Cr\u00e9ation des miniatures","progress":70}
{"message":"Cr\u00e9ation des miniatures","progress":80}
{"message":"Cr\u00e9ation des miniatures effectu\u00e9e avec succ\u00e8s","progress":90}
{"message":"Upload du\/des fichier(s) termin\u00e9 avec succ\u00e8s","progress":100,"status":"success"}
```
### Exemple du format conforme : 
```json
[{"message":"Contr\u00f4le des donn\u00e9es","progress":10},
{"message":"Cr\u00e9ation des miniatures","progress":70},
{"message":"Cr\u00e9ation des miniatures","progress":80},
{"message":"Cr\u00e9ation des miniatures effectu\u00e9e avec succ\u00e8s","progress":90},
{"message":"Upload du\/des fichier(s) termin\u00e9 avec succ\u00e8s","progress":100,"status":"success"}]
```

**Comment by Xarksass** [comment]
Le problème c'est pas le json mais le retour de progression continu au niveau php qui est souvent bloqué en production.
Si le résultat n'est pas "conforme" c'est parce que normalement chaque objet json est envoyé séparément au fur et à mesure pour indiquer la progression sauf que lorsque le système est bloqué tout est envoyé d'un coup.
