### ISSUE TITLE
Bug langues menu

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms-3#147]
Lorsqu'on ajoute le lien vers la racine des news dans le menu et qu'on ajoute/active des langues à posteriori, il est impossible de modifier ou d'activer le lien pour la/les langue(s) ajoutée(s) (pour le systeme, le module n'est pas actif dans cette langue la, ce qui n'est pas possible).
À voir avec les autres root de module.

**Comment by gtraxx** [comment]
Attention que dans l'admin on sait ajouter les langues inactive pour plus tard, je ne sais pas si c'est lié
