### ISSUE TITLE
Liste des nouveaux champs produits

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#15]
Actuellement, le catalogue des produits affiche le nom, l'image, la description, le prix (optionnel).
Dans cette version il nous faudrait compléter cette liste : 
* Nom
* Description
* Prix
**Nouveaux champs possible :** 
* Référence ou numéro de référence
* Largeur
* Hauteur 
* Profondeur
* Poids
* Produit disponible (Oui ou Non)
### Les images du produit
Table indépendante pour ajouter plusieurs images et choisir la principal du produit

**Comment by Xarksass** [comment]
+ Courte description / résumé

**Comment by gtraxx** [comment]
Ajouter prix TTC (non stocké) utilisé pour calculer le prix HT
