### ISSUE TITLE
Liste des réseaux sociaux disponible dans About

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#16]
Voici la liste disponible et ceux a ajouter : 
* Facebook
* Twitter
* Linkedin
* Viadeo
* Googleplus

A ajouter ou permettre de pouvoir les ajouter ?

* Pinterest
* Instagram
* Github
* Soundcloud
@Xarksass tu en vois d'autres ?

**Comment by Xarksass** [comment]
Il faudra aussi essayer de faire en sorte que sur mobile le lien tente d'ouvrir l'appli relative au réseau social en question.

**Comment by Xarksass** [comment]
Les liens pour :
- Pinterest
- Instagram
- Github
- Soundcloud
ont été ajoutés.

Je pensais peut être ajouter aussi :
- Tumblr ?
- Flickr ?
- 500px ?
- Snapchat ?

Tu en vois d'autres ?
