### ISSUE TITLE
javascript applicatif

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#2]
Le javascript exécutif tel que l'envoi des données de formulaire et autres sera générique mais doit il être global au frontend et backend ? ou une gestion séparé des deux parties ?

**Comment by Xarksass** [comment]
Mieux vaut en deux partie si le javascript dédié au backend est sensiblement plus important que celui dédié au frontend, ce qui sera surement le cas.

**Comment by gtraxx** [comment]
Effectivement :)
