### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#20]
possibilité de générer un fichier Robots.txt
Par défaut
User-Agent: *
Disallow: 

identifier si disallow admin ou autres @gtraxx @Xarksass

**Comment by gtraxx** [comment]
C'est plutôt : 
`User-agent: *
Allow: /`

**Comment by gtraxx** [comment]
@phytoman voila dans les paramètres de configuration, lorsque vous choisissez robots : no index ou index, il adaptera le fichier en fonction du choix.
