### ISSUE TITLE
Horaires d'ouverture

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#28]
1) Lorsqu'un client insère des heures d'ouverture de 08 à 18h pour chaque jour, la deuxième colonne s'affiche avec comme titre "et entre". Il faudrait gérer une exception qui dit "si pas de rupture de temps de midi ne pas afficher la deuxième colonne.
2) Il est fréquent de voir des indépendants ne possédant pas de locaux. Est-il possible d'avoir dans le module Horaire un bouton "Par téléphone" afin que du coté public soit affiché "Vous pouvez nous contacter par téléphone ou Gsm de :"

**Comment by Xarksass** [comment]
1. Les libellés ont été retiré pour plus de simplicité.
2. Il suffit d'enregistrer le numéro de téléphone dans le module "À propos".
