### ISSUE TITLE
Pagination dans les actualités

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms-3#34]
Page root des actualités
-
Mettre en place deux types de navigation :
+ précédent - (1,2,3,...) - suivant
+ articles plus anciens - articles plus récent

Page actualité
-
Mettre en place une pagination de type "article précédent - article suivant" (utile pour indiquer une relation d'ordre entre les articles)

**Comment by gtraxx** [comment]
Je ne sais pas si c'est en place ?

**Comment by Xarksass** [comment]
Pagination mise en place et réutilisable par d'autre modules.
