### ISSUE TITLE
Gestion des partages

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms-3#41]
Ajouter gestion des partages dans l'admin:
- Sélection des boutons de partage souhaités;
- Ajout de l'identifiant Twitter pour générer des twitter cards;
- Ajouter des réseaux sociaux supplémentaire pour le partage tel que Pinterest
(Étudier l'api de Pinterest, elle permet des choses intéressantes: reconnaissance de produit etc)

**Comment by Xarksass** [comment]
Ajouter la possibilité d'ajouter/éditer/supprimer des réseaux sociaux pour les partages.

**Comment by gtraxx** [comment]
@Xarksass Est ce terminé ?
