### ISSUE TITLE
Affichage des pages dans le menu - activer/désactiver

### ISSUE THREAD

**Issue by Xarksass** [magix-cms/magixcms-3#47]
Mettre en place le système pour activer/désactiver l'affiche d'une page dans le menu.

Étendre cette fonction aux catégories.

**Comment by gtraxx** [comment]
Dans le backend c'est déjà opérationnel pour les pages CMS, faut il le faire dans les catégories ?

**Comment by gtraxx** [comment]
Je viens de l'ajouter dans les categories :)

**Comment by gtraxx** [comment]
@Xarksass attention bug sur le bouton "activer la sélection" dans les pages enfants !!!
