### ISSUE TITLE
Bug activation d'une page enfant pour le menu

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#58]
Si on souhaite activer une page enfant dans le menu, le rafraîchissement ne ce fait pas correctement.
Obliger de rafraîchir la page manuellement.
![screenshot-2018-3-27 editer une pages magix cms admin png](https://user-images.githubusercontent.com/356674/37956434-abe8462c-31ab-11e8-93a6-813b4e06e9fb.png)

**Comment by Xarksass** [comment]
Corrigé avec la mise à jour de table-form
