### ISSUE TITLE
block main-cat

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#63]
Le block main-cat ne fonctionne pas, impossible de remonter les 3 blocks en page d'accueil.
id_mainCat n'est défini null part et on ne sait ps comment l'utiliser

**Comment by gtraxx** [comment]
@Xarksass adapter le block-cat avec les modifications de performances et les modifications dans le "model"

**Comment by Xarksass** [comment]
Fonctionne à nouveau et peut être recréé avec les variables de traduction (comme précédemment) mais il serait plus facile et logique de gérer ce bloc avec un plugin.

**Comment by Xarksass** [comment]
Module "mainsectors" créé à cet effet.
Il permet de choisir parmi les pages et les catégories, celles que l'on souhaite voir apparaître sur la page d'accueil.
