### ISSUE TITLE
Bug moteur de recherche backend

### ISSUE THREAD

**Issue by gtraxx** [magix-cms/magixcms-3#70]
Si j'utilise une apostrophe dans le moteur de recherche il plante le backend, il faut modifier la/les requêtes de recherches ou nettoyer les données POST

**Comment by Xarksass** [comment]
Corrigé à priori, à vérifier.

**Comment by gtraxx** [comment]
@Xarksass plus aucune recherche ne fonctionne avec ce type de requête, le paramètre de langue est effacé/écrasé et si même je balance en dur la langue, aucune recherche n'abouti depuis ce changement

`if(isset($config['search'])) {
						$cond = '';
						$config['search'] = array_filter($config['search']);
                    	if(is_array($config['search']) && !empty($config['search'])) {
							$nbc = 0;
							$params = array();
							foreach ($config['search'] as $key => $q) {
								if($q != '') {
									$cond .= 'AND ';
									$params[$key] = $q;
									switch ($key) {
										case 'id_pages':
										case 'published_pages':
											$cond .= 'c.'.$key.' = :'.$key.' ';
											break;
										case 'name_pages':
											$cond .= "c.".$key." LIKE '%:".$key."%' ";
											break;
										case 'parent_pages':
											$cond .= "ca.name_pages"." LIKE '%:".$key."%' ";
											break;
										case 'menu_pages':
											$cond .= 'p.'.$key.' = :'.$key.' ';
											break;
										case 'date_register':
											$q = $dateFormat->date_to_db_format($q);
											$cond .= "p.".$key." LIKE '%:".$key."%' ";
											$params[$key] = $q;
											break;
									}
									$nbc++;
								}
							}

							$sql = "SELECT p.id_pages, c.name_pages, c.content_pages, c.seo_title_pages, c.seo_desc_pages, p.menu_pages, p.date_register, ca.name_pages AS parent_pages
								FROM mc_cms_page AS p
									JOIN mc_cms_page_content AS c USING ( id_pages )
									JOIN mc_lang AS lang ON ( c.id_lang = lang.id_lang )
									LEFT JOIN mc_cms_page AS pa ON ( p.id_parent = pa.id_pages )
									LEFT JOIN mc_cms_page_content AS ca ON ( pa.id_pages = ca.id_pages ) 
									WHERE c.id_lang = :default_lang $cond
									GROUP BY p.id_pages 
								ORDER BY p.order_pages";
						}
                    }`

**Comment by Xarksass** [comment]
La correction à été corrigée.
