### ISSUE TITLE
Arborescence explorateur catégories

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#73]
Lorsqu'on veut associer une catégorie ou une sous-catégorie à un produit et que la liste est importante, lors du clic sur la catégorie, l'arborescence n'est pas fixé à la première ligne, ce qui oblige à scroller pour trouver certains éléments

**Comment by Xarksass** [comment]
Une capture d'écran ou un exemple concret seraient les bienvenus

**Comment by Xarksass** [comment]
Une capture d'écran ou un exemple concret seraient les bienvenus.

**Comment by phytoman** [comment]
@Xarksass nouveau site solbreux
