### ISSUE TITLE
Affichage points de vente Gmap

### ISSUE THREAD

**Issue by phytoman** [magix-cms/magixcms-3#78]
@gtraxx @gtraxx 
le plugin est installé mais quand j'injecte une image et du texte dans une adresse, ces données ne sont pas envoyées au serveur (zones vides après rechargement).
Pas d'affichage coté public

**Comment by Xarksass** [comment]
Correction du bug de l'affichage dans l'admin.

Les adresses ne sont remontées côté public qu'à partir du moment où il y en a au moins deux d'encodées.

**Comment by phytoman** [comment]
@Xarksass Non fonctionnel sur multisite ?!
